const GWKEY='sati.gateway.url',DEFAULT_GW='http://127.0.0.1:8787';let GW=localStorage.getItem(GWKEY)||DEFAULT_GW;let S={status:null,auto:null,analytics:null,leads:[],discover:[],online:false};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const pct=n=>`${Number(n||0).toFixed(Number(n||0)%1?1:0)}%`;const fmtDate=v=>v?new Date(v).toLocaleString(): '—';const cap=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const pages=[['overview','Overview','Live sales performance'],['leads','Priority Leads','Ranked 0–100 lead queue'],['outreach','Outreach','Queue and sent history'],['replies','Replies','Inbound and positive pipeline'],['analytics','Analytics','Success, reply and channel rates'],['discovery','Discovery','Search business opportunities'],['sources','Sources & Channels','Health and connections'],['settings','Settings','Automation controls']];
function nav(){const n=$('nav'),m=$('mobile');n.innerHTML='<h6>SALES CONTROL</h6>'+pages.map(([id,name])=>`<button data-page="${id}" onclick="go('${id}')">${name}</button>`).join('');m.innerHTML=pages.slice(0,6).map(([id,name])=>`<button data-page="${id}" onclick="go('${id}')">${name}</button>`).join('')}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('on',x.id===id));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('on',x.dataset.page===id));const p=pages.find(x=>x[0]===id)||pages[0];$('title').textContent=p[1];$('subtitle').textContent=p[2];location.hash=id}
async function api(path,opt={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(GW+path,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})},signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed ${r.status}`);return d}finally{clearTimeout(t)}}
function badge(id,kind,text){const e=$(id);if(!e)return;e.className=`badge ${kind||''}`;e.textContent=text}
function lifecycleLabel(l){return l==='opening_soon'?'Opening soon':l==='new_business'?'New business':l==='newly_discovered'?'Newly discovered':l==='ongoing'?'Ongoing':'Unknown'}
function routeOf(l){if(l.lastOutbound)return l.lastOutbound;if(l.whatsappConsent&&l.whatsapp)return'whatsapp';if(l.email)return'email';return l.platform||'business'}
function leadSentAt(l){return l.whatsappSentAt||l.emailSentAt||l.lastOutboundAt||null}
function priorityClass(l){return (l.priorityBand||((l.priority||l.score)>=80?'high':(l.priority||l.score)>=55?'medium':'low'))}
function scoreVal(l){return Math.round(Number(l.priority??l.score??0))}
function kpi(label,value,note){return `<div class="card kpi"><small>${esc(label)}</small><b>${esc(value)}</b><em>${esc(note||'')}</em></div>`}
function metric(label,val,max=100){const n=Math.max(0,Number(val||0)),w=max?Math.min(100,(n/max)*100):0;return `<div class="metric-row"><span>${esc(label)}</span><div class="progress"><i style="width:${w}%"></i></div><b>${esc(n)}</b></div>`}
function eventHtml(e){return `<div class="activity"><b>${esc(cap(e.type||'event'))}</b> · ${esc(e.message||'')}<small>${fmtDate(e.at)}</small></div>`}
function renderOverview(){const a=S.auto?.analytics||S.analytics||{},c=S.auto?.counters||{},pc=a.priorityCounts||{},lc=a.lifecycleCounts||{},status=S.auto?.statusCounts||{};$('kpis').innerHTML=[kpi('Lead pool',S.auto?.leadCount||S.leads.length,'deduped prospect records'),kpi('High priority',pc.high||0,'80–100 score'),kpi('Sent',c.sent||0,'real sends only'),kpi('Replies',c.replies||0,pct(a.replyRate)+' reply rate'),kpi('Positive',c.positiveReplies||0,pct(a.positiveReplyRate)+' of replies'),kpi('Success rate',pct(a.positivePerSent),'positive ÷ sent'),kpi('Non-bounce',pct(a.nonBounceRate),'sent minus known bounces'),kpi('Closed',c.closed||status.closed||0,pct(a.closeRate)+' close rate')].join('');
 const lead=S.auto?.leadCount||1;$('priorityDist').innerHTML=metric('High',pc.high||0,lead)+metric('Medium',pc.medium||0,lead)+metric('Low',pc.low||0,lead);$('lifeDist').innerHTML=metric('Opening soon',lc.opening_soon||0,lead)+metric('New business',lc.new_business||0,lead)+metric('Newly discovered',lc.newly_discovered||0,lead)+metric('Ongoing',lc.ongoing||0,lead);
 const funnel=[['Discovered',c.discovered||S.auto?.leadCount||0],['Contacted',status.contacted||0],['Replies',c.replies||0],['Positive',c.positiveReplies||0],['Proposal',status.proposal||0],['Closed',c.closed||status.closed||0]];$('funnel').innerHTML=funnel.map(x=>`<div class="step"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');$('activity').innerHTML=(S.auto?.recent||[]).slice(0,10).map(eventHtml).join('')||'<div class="empty">No recent automation events yet.</div>'
}
function filteredLeads(){let r=S.leads.slice(),q=$('leadSearch')?.value?.toLowerCase().trim()||'',p=$('leadPriority')?.value||'',life=$('leadLife')?.value||'',plat=$('leadPlatform')?.value||'',st=$('leadStatus')?.value||'';if(q)r=r.filter(x=>`${x.name} ${x.city} ${x.category}`.toLowerCase().includes(q));if(p)r=r.filter(x=>priorityClass(x)===p);if(life)r=r.filter(x=>x.lifecycle===life);if(plat)r=r.filter(x=>x.platform===plat||x.lastOutbound===plat);if(st)r=r.filter(x=>x.status===st);return r.sort((a,b)=>(b.priority||b.score||0)-(a.priority||a.score||0))}
function renderLeads(){const r=filteredLeads();$('leadCount').textContent=`${r.length} leads`;$('leadEmpty').style.display=r.length?'none':'block';$('leadRows').innerHTML=r.map(l=>{const pc=priorityClass(l),routes=[l.email?'email':'',l.whatsapp?'whatsapp':'',...Object.keys(l.socials||{})].filter(Boolean);return `<tr><td><b>${esc(l.name)}</b><div class="tiny">${esc(l.senderLane||'')}</div></td><td><span class="score ${pc}">${scoreVal(l)}%</span> <span class="badge ${pc}">${pc}</span></td><td>${esc(lifecycleLabel(l.lifecycle))}${l.businessStartDate?`<div class="tiny">${esc(l.businessStartDate)}</div>`:''}</td><td>${esc(l.city||'—')}</td><td>${esc(cap(l.category))}</td><td>${l.hasWebsite?'<span class="badge">Listed</span>':'<span class="badge high">No website listed</span>'}</td><td>${esc(routes.join(', ')||l.platform||'—')}</td><td>${esc(cap(l.status||'new'))}</td><td>${esc(fmtDate(leadSentAt(l)))}</td><td><div class="actions"><button class="btn" onclick='showLead(${JSON.stringify(l.key)})'>View</button>${l.sampleUrl?`<a class="btn" href="${esc(l.sampleUrl)}" target="_blank">Sample</a>`:''}</div></td></tr>`}).join('')}
function renderOutreach(){const queue=S.leads.filter(l=>!leadSentAt(l)&&!['dnc','bounced','lost','closed'].includes(l.status)).sort((a,b)=>scoreVal(b)-scoreVal(a)).slice(0,18);$('queueBadge').textContent=`${queue.length} next`;$('queueList').innerHTML=queue.map((l,i)=>`<div class="lead"><b>#${i+1} · ${esc(l.name)}</b> <span class="score ${priorityClass(l)}">${scoreVal(l)}%</span><small>${esc(lifecycleLabel(l.lifecycle))} · ${esc(l.city)} · ${esc(cap(l.category))} · next route: ${esc(routeOf(l))}</small></div>`).join('')||'<div class="empty">No eligible queued leads.</div>';const day=S.auto?.day?.sent||{},caps=S.auto?.dailyCaps||{};$('dailyUsage').innerHTML=['email','whatsapp','total'].map(k=>{const used=day[k]||0,capv=caps[k]||0;return `<div class="metric-row"><span>${cap(k)}</span><div class="progress"><i style="width:${capv?Math.min(100,used/capv*100):0}%"></i></div><b>${used}/${capv}</b></div>`}).join('');const sent=S.leads.filter(l=>leadSentAt(l)).sort((a,b)=>new Date(leadSentAt(b))-new Date(leadSentAt(a)));$('sentRows').innerHTML=sent.slice(0,200).map(l=>`<tr><td><b>${esc(l.name)}</b></td><td><span class="score ${priorityClass(l)}">${scoreVal(l)}%</span></td><td class="truncate">${esc(l.lastOutbound==='whatsapp'?l.whatsapp:l.email||l.phone||'—')}</td><td>${esc(l.lastOutbound||routeOf(l))}</td><td class="truncate">${esc(l.senderLane||'—')}</td><td>${esc(fmtDate(leadSentAt(l)))}</td><td>${esc(cap(l.status))}</td></tr>`).join('')}
function renderReplies(){const replies=S.leads.filter(l=>l.lastReplyAt).sort((a,b)=>new Date(b.lastReplyAt)-new Date(a.lastReplyAt));$('replyList').innerHTML=replies.map(l=>`<div class="lead"><b>${esc(l.name)}</b> · ${esc(cap(l.status))}<small>${esc(l.lastReplySnippet||'Reply detected')} · ${fmtDate(l.lastReplyAt)}</small></div>`).join('')||'<div class="empty">No replies detected yet.</div>';const pos=S.leads.filter(l=>['positive','interested','proposal','closed'].includes(l.status)).sort((a,b)=>scoreVal(b)-scoreVal(a));$('positiveList').innerHTML=pos.map(l=>`<div class="lead"><b>${esc(l.name)}</b> · ${esc(cap(l.status))} <span class="score ${priorityClass(l)}">${scoreVal(l)}%</span><small>${esc(l.city)} · ${esc(cap(l.category))}</small></div>`).join('')||'<div class="empty">No positive pipeline records yet.</div>'}
function renderAnalytics(){const a=S.auto?.analytics||S.analytics||{},c=S.auto?.counters||{};$('aReply').textContent=pct(a.replyRate);$('aPositive').textContent=pct(a.positiveReplyRate);$('aSuccess').textContent=pct(a.positivePerSent);$('aClose').textContent=pct(a.closeRate);const cs=a.channelStats||{};$('channelPerf').innerHTML=Object.entries(cs).sort((a,b)=>(b[1].sent||0)-(a[1].sent||0)).map(([k,v])=>`<div class="channel"><b>${esc(cap(k))}</b><small>Leads ${v.leads||0} · Sent ${v.sent||0}<br>Replies ${v.replies||0} · Positive ${v.positive||0}<br>Bounced ${v.bounced||0}</small></div>`).join('')||'<div class="empty">No channel data yet.</div>';$('qualityControls').innerHTML=[['Duplicate sends suppressed',c.duplicatesSuppressed||0],['Policy-blocked unsafe sends',c.blockedByPolicy||0],['Known bounces',c.bounces||0],['Do-not-contact',c.dnc||0],['Automation errors',c.errors||0]].map(x=>`<div class="activity"><b>${esc(x[0])}</b><small>${x[1]}</small></div>`).join('')}
function renderSources(){const h=S.auto?.sourceHealth||{};$('sourceHealth').innerHTML=Object.keys(h).length?Object.entries(h).map(([k,v])=>`<div class="source ${v.status==='ok'?'ok':'bad'}"><b>${esc(cap(k))}</b><small>${esc(v.status)} · checked ${esc(fmtDate(v.lastCheckedAt))}${v.lastError?`<br>${esc(v.lastError)}`:''}${v.city?`<br>${esc(v.city)} / ${esc(v.category||'')}`:''}</small></div>`).join(''):'<div class="empty">No source checks recorded yet.</div>';const ps=S.status?.platforms||{};$('channelHealth').innerHTML=Object.entries(ps).map(([k,v])=>`<div class="source ${v.connected?'ok':''}"><b>${esc(cap(k))}</b><small>${v.connected?'Connected':'Not connected'}<br>${esc(v.send||v.discovery||'Capability depends on provider/account permissions')}</small></div>`).join('')||'<div class="empty">Gateway status unavailable.</div>'}
function renderSettings(){const a=S.auto||{};$('setEnabled').checked=!!a.enabled;$('setDiscovery').checked=!!a.discoveryEnabled;$('setEmail').checked=!!a.emailOutreach;$('setWa').checked=!!a.authorizedAutoSend;$('setInterval').value=a.intervalMinutes||15;$('capEmail').value=a.dailyCaps?.email??150;$('capWa').value=a.dailyCaps?.whatsapp??30;$('capTotal').value=a.dailyCaps?.total??180;$('mixHigh').value=a.priorityMix?.high??70;$('mixMedium').value=a.priorityMix?.medium??25;$('mixLow').value=a.priorityMix?.low??5}
function renderHeader(){const ps=S.status?.platforms||{},connected=Object.values(ps).filter(x=>x.connected).length;$('sideConn').textContent=`${connected} channels connected`;$('hConn').textContent=String(connected);$('hNext').textContent=S.auto?.nextRun?new Date(S.auto.nextRun).toLocaleTimeString():'—';$('fPool').textContent=String(S.auto?.leadCount||0);$('fAuto').textContent=S.auto?.enabled?'ON':'Paused';$('hAuto').textContent=S.auto?.busy?'Running':S.auto?.enabled?'Enabled':'Paused';if(S.online){badge('gwBadge','ok',`Gateway v${S.status?.version||'0.9'} online`);$('fGw').textContent='Online';$('hGw').textContent='Online'}else{badge('gwBadge','bad','Gateway offline');$('fGw').textContent='Offline';$('hGw').textContent='Offline'}}
function renderAll(){renderHeader();renderOverview();renderLeads();renderOutreach();renderReplies();renderAnalytics();renderSources();renderSettings()}
async function refreshAll(){try{const [status,auto,leads,analytics]=await Promise.all([api('/status'),api('/automation/status'),api('/automation/leads?limit=700'),api('/automation/analytics')]);S.status=status;S.auto=auto;S.leads=leads.leads||[];S.analytics=analytics;S.online=true}catch(e){S.online=false;console.warn(e)}renderAll()}
async function runNow(){if(!S.online){alert('Local Sati Gateway is offline. Start it first.');return}badge('gwBadge','warn','Running cycle…');try{const d=await api('/automation/run-now',{method:'POST',body:'{}'});await refreshAll();alert(`Cycle complete: ${d.indiaAdded||0} India + ${d.globalAdded||0} global leads, ${d.outreach?.sent||0} sends.`)}catch(e){alert(e.message);await refreshAll()}}
async function setLeadStatus(key,status){try{await api('/automation/lead-status',{method:'POST',body:JSON.stringify({leadKey:key,status})});await refreshAll()}catch(e){alert(e.message)}}
function showLead(key){const l=S.leads.find(x=>x.key===key);if(!l)return;$('modalSub').textContent=`${scoreVal(l)}% ${priorityClass(l)} · ${lifecycleLabel(l.lifecycle)} · ${l.city||''}`;$('modalBody').textContent=`Business: ${l.name}\nCategory: ${cap(l.category)}\nPriority: ${scoreVal(l)}% (${priorityClass(l)})\nLifecycle: ${lifecycleLabel(l.lifecycle)}${l.businessStartDate?' · '+l.businessStartDate:''}\nWebsite: ${l.hasWebsite?(l.website||'listed'):'No website listed in source'}\nEmail: ${l.email||'—'}\nPhone: ${l.phone||'—'}\nWhatsApp: ${l.whatsapp||'—'}\nPlatform: ${l.platform||'—'}\nProfile: ${l.profileUrl||'—'}\nStatus: ${l.status||'new'}\nLast sent: ${fmtDate(leadSentAt(l))}\nLast reply: ${l.lastReplySnippet||'—'}\nSender lane: ${l.senderLane||'—'}\nReason: ${l.lifecycleReason||'—'}`;$('modalActions').innerHTML=`${l.sampleUrl?`<a class="btn primary" href="${esc(l.sampleUrl)}" target="_blank">Open sample</a>`:''}${l.profileUrl?`<a class="btn" href="${esc(l.profileUrl)}" target="_blank">Open profile</a>`:''}<button class="btn good" onclick='setLeadStatus(${JSON.stringify(l.key)},"interested")'>Interested</button><button class="btn" onclick='setLeadStatus(${JSON.stringify(l.key)},"proposal")'>Proposal</button><button class="btn good" onclick='setLeadStatus(${JSON.stringify(l.key)},"closed")'>Closed</button><button class="btn danger" onclick='setLeadStatus(${JSON.stringify(l.key)},"dnc")'>DNC</button>`;$('msgModal').classList.add('on')}
function closeModal(){$('msgModal').classList.remove('on')}
const categories=['hotel','resort','guest_house','hostel','restaurant','cafe','fast_food','bar','real_estate','architect','builder','interior','school','college','university','kindergarten','hospital','clinic','doctors','dentist','pharmacy','physiotherapist','veterinary','gym','sports_centre','salon','beauty','spa','supermarket','clothes','furniture','electronics','mobile_phone','jewelry','hardware','florist','bakery','travel_agent','lawyer','accountant','insurance','advertising','photographer','car_dealer','car_repair','car_rental'];
function initCategories(){$('discoverCategory').innerHTML=categories.map(c=>`<option value="${c}">${cap(c)}</option>`).join('')}
async function discoverBusinesses(){if(!S.online){alert('Start Sati Gateway first.');return}badge('discoverBadge','warn','Searching…');$('discoverRows').innerHTML='';$('discoverEmpty').style.display='block';try{const city=$('discoverCity').value.trim(),category=$('discoverCategory').value,d=await api(`/discover/businesses?city=${encodeURIComponent(city)}&category=${encodeURIComponent(category)}`);S.discover=d.businesses||[];badge('discoverBadge','ok',`${S.discover.length} businesses`);$('discoverEmpty').style.display=S.discover.length?'none':'block';$('discoverRows').innerHTML=S.discover.map((b,i)=>`<tr><td><b>${esc(b.name)}</b><div class="tiny">${esc(b.city||'')}</div></td><td><span class="score ${esc(b.priorityBand||'low')}">${Math.round(b.priority||0)}%</span></td><td>${esc(lifecycleLabel(b.lifecycle))}${b.businessStartDate?`<div class="tiny">${esc(b.businessStartDate)}</div>`:''}</td><td>${b.hasWebsite?'<span class="badge">Listed</span>':'<span class="badge high">No website</span>'}</td><td>${esc(b.phone||b.whatsapp||'—')}</td><td>${esc(b.email||'—')}</td><td class="truncate">${esc(Object.keys(b.socials||{}).join(', ')||'—')}</td><td><button class="btn" onclick="importBusiness(${i})">Add to queue</button></td></tr>`).join('')}catch(e){badge('discoverBadge','bad','Search failed');$('discoverEmpty').textContent=e.message}}
async function importBusiness(i){const b=S.discover[i];if(!b)return;try{await api('/automation/import-business',{method:'POST',body:JSON.stringify({business:b,scope:'manual'})});await refreshAll();alert(`${b.name} added to priority queue.`)}catch(e){alert(e.message)}}
async function findPlatformRoutes(){if(!S.online){alert('Start Sati Gateway first.');return}const city=$('discoverCity').value.trim(),category=$('discoverCategory').value;badge('discoverBadge','warn','Checking platform routes…');try{const d=await api(`/discover?city=${encodeURIComponent(city)}&category=${encodeURIComponent(category)}`),r=d.leads||[];$('platformResults').innerHTML=r.map(x=>`<div class="lead"><b>${esc(x.business_name)}</b> · ${esc(cap(x.platform))} · <span class="score ${x.priority_band||'low'}">${Math.round(x.lead_score||0)}%</span><small>${esc(x.city)} · ${esc(cap(x.category))} · ${esc(x.lifecycle||'unknown')}${x.profile_url?` · <a href="${esc(x.profile_url)}" target="_blank" style="color:#73cfff">open profile</a>`:''}${x.public_email?` · ${esc(x.public_email)}`:''}</small></div>`).join('')||'<div class="empty">No exact public platform/contact routes found for this category/city scan.</div>';badge('discoverBadge','ok',`${r.length} verified routes`)}catch(e){badge('discoverBadge','bad','Route check failed');$('platformResults').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function saveSettings(){try{const priorityMix={high:Number($('mixHigh').value||70),medium:Number($('mixMedium').value||25),low:Number($('mixLow').value||5)};const total=priorityMix.high+priorityMix.medium+priorityMix.low;if(total!==100)return alert('Priority mix must total 100%.');const body={enabled:$('setEnabled').checked,discoveryEnabled:$('setDiscovery').checked,emailOutreach:$('setEmail').checked,authorizedAutoSend:$('setWa').checked,intervalMinutes:Number($('setInterval').value||15),dailyCaps:{email:Number($('capEmail').value||0),whatsapp:Number($('capWa').value||0),total:Number($('capTotal').value||0)},priorityMix};await api('/automation/config',{method:'POST',body:JSON.stringify(body)});await refreshAll();alert('Automation settings saved.')}catch(e){alert(e.message)}}
window.addEventListener('load',async()=>{nav();initCategories();go((location.hash||'#overview').slice(1));await refreshAll();setInterval(refreshAll,15000)});window.addEventListener('hashchange',()=>go((location.hash||'#overview').slice(1)));