import crypto from 'node:crypto';
const INDIA_BBOX='6.5,68.0,37.5,97.5';
export const CATS={hotel:[['tourism','hotel']],resort:[['tourism','resort']],restaurant:[['amenity','restaurant']],cafe:[['amenity','cafe']],hospital:[['amenity','hospital']],clinic:[['amenity','clinic']],school:[['amenity','school']],real_estate:[['office','estate_agent']],gym:[['leisure','fitness_centre']],salon:[['shop','hairdresser']]};
export const cleanPhone=(v='')=>{const s=String(v).replace(/[^0-9+]/g,'');if(!s)return'';if(s.startsWith('+'))return s;if(s.startsWith('91')&&s.length>=12)return'+'+s;if(s.length===10)return'+91'+s;return s};
export const hasWebsite=t=>Boolean(t.website||t['contact:website']||t.url);
export function msg(l){const hooks=[`I came across ${l.name} while researching strong local businesses in ${l.city||l.state||'your area'}.`,`${l.name} stood out while I was reviewing businesses in ${l.city||l.state||'your area'}, and I noticed a digital growth opportunity.`,`While checking established businesses in ${l.city||l.state||'your area'}, I found ${l.name} and wanted to share one quick idea.`,`Your customer reputation gives ${l.name} a strong base; I noticed one online opportunity that could turn more searches into direct enquiries.`];const ben={hotel:'direct booking enquiries, room showcases and local search visibility',resort:'direct stay enquiries, premium galleries and booking-focused pages',restaurant:'menu discovery, table enquiries and local search visibility',cafe:'menu discovery, location actions and a premium online presence',hospital:'service discovery, appointment enquiries and trust-building pages',clinic:'appointment enquiries, doctor information and local visibility',school:'admission enquiries, parent information and search visibility',real_estate:'property enquiries, listing showcases and lead capture',gym:'membership enquiries and local lead capture',salon:'service discovery, appointment enquiries and local visibility'};const seed=parseInt(crypto.createHash('md5').update(l.id).digest('hex').slice(0,8),16);return `Hi ${l.name} team, ${hooks[seed%hooks.length]}\n\n${!l.hasWebsite?'I could not find a dedicated website for your business':'I reviewed your current online presence'}, which may be leaving potential enquiries on the table. Sati Technologies can build or improve a fast, mobile-first website focused on ${ben[l.category]||'customer enquiries and stronger online visibility'}.\n\nIf useful, I can share a quick concept tailored specifically for ${l.name}.`}
export function score(l){return(!l.hasWebsite?60:0)+(l.phone?15:0)+(l.whatsapp?10:0)+(l.name?5:0)+(l.city||l.state?5:0)+5}
export async function overpass(category,city){const pairs=CATS[category]||CATS.hotel;const safeCity=city.replace(/"/g,'');const area=city?`area["name"="${safeCity}"]["boundary"="administrative"]->.a;`:'';const scope=city?'(area.a)':`(${INDIA_BBOX})`;const sels=pairs.map(([k,v])=>`nwr["${k}"="${v}"]["name"]${scope};`).join('\n');const q=`[out:json][timeout:20];${area}(${sels});out center tags 120;`;for(const ep of ['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter']){try{const r=await fetch(ep,{method:'POST',body:q,headers:{'content-type':'text/plain','user-agent':'SatiLeadEngine/0.1'}});if(r.ok)return await r.json()}catch{}}throw new Error('Free public lead source unavailable right now')}
export function normalize(data,category,city,onlyNo=true){return(data.elements||[]).map(el=>{const t=el.tags||{},phone=cleanPhone(t['contact:phone']||t.phone||t['contact:mobile']||t.mobile||''),whatsapp=cleanPhone(t['contact:whatsapp']||t.whatsapp||'');const l={id:`osm-${el.type}-${el.id}`,source:'osm',name:t.name||'',category,city:t['addr:city']||t['addr:town']||city||'',state:t['addr:state']||'',phone,whatsapp,hasWebsite:hasWebsite(t),website:t.website||t['contact:website']||t.url||'',lat:el.lat??el.center?.lat??null,lon:el.lon??el.center?.lon??null};l.score=score(l);l.message=msg(l);const target=l.whatsapp||l.phone;l.whatsappLink=target?`https://wa.me/${target.replace(/\D/g,'')}?text=${encodeURIComponent(l.message)}`:'';return l}).filter(l=>l.name).filter(l=>!onlyNo||!l.hasWebsite).sort((a,b)=>b.score-a.score)}
