export const demos = [
  {
    id: 'commerce',
    number: '01',
    eyebrow: 'E-commerce',
    title: '3D Product Studio',
    shortTitle: 'Commerce',
    description: 'A tactile product configurator that turns browsing into an interactive buying experience.',
    accent: '#77f7d2',
    secondary: '#4f7cff',
    stat: '+34% engagement',
    tags: ['3D Configurator', 'Cart-ready', 'Mobile-first'],
    features: ['Real-time colour and finish controls', 'Interactive orbit and product details', 'Conversion-focused product storytelling'],
    modes: ['Studio', 'Midnight', 'Editorial'],
  },
  {
    id: 'real-estate',
    number: '02',
    eyebrow: 'Real estate',
    title: 'Virtual Property Tour',
    shortTitle: 'Real Estate',
    description: 'An explorable property presentation designed to help buyers understand a project before a site visit.',
    accent: '#ffbd69',
    secondary: '#ff6f91',
    stat: '24/7 open house',
    tags: ['Virtual Tour', 'Lead Capture', 'Project Map'],
    features: ['Day and night environment modes', 'Interactive building visualisation', 'Brochure, enquiry and WhatsApp flows'],
    modes: ['Golden hour', 'Daylight', 'Night'],
  },
  {
    id: 'hospitality',
    number: '03',
    eyebrow: 'Hospitality',
    title: 'Immersive Dining',
    shortTitle: 'Hospitality',
    description: 'A cinematic restaurant experience with interactive menus, ambience and reservation journeys.',
    accent: '#ff8b7b',
    secondary: '#ffc857',
    stat: '2-click booking',
    tags: ['Interactive Menu', 'Reservations', 'Local SEO'],
    features: ['Visual signature-dish storytelling', 'Reservation and WhatsApp ordering', 'Events, offers and location integration'],
    modes: ['Chef table', 'Dinner', 'Celebration'],
  },
  {
    id: 'saas',
    number: '04',
    eyebrow: 'SaaS & dashboards',
    title: 'Live Intelligence',
    shortTitle: 'SaaS',
    description: 'A real-time command centre that makes complex business data easy to understand and act on.',
    accent: '#8d9cff',
    secondary: '#58e6ff',
    stat: '<1s live updates',
    tags: ['Live Data', 'Role-based UI', 'Analytics'],
    features: ['Streaming metric visualisation', 'Responsive operational dashboard', 'API, auth and notification-ready UI'],
    modes: ['Overview', 'Revenue', 'Operations'],
  },
  {
    id: 'events',
    number: '05',
    eyebrow: 'Events & entertainment',
    title: 'Digital Stage',
    shortTitle: 'Events',
    description: 'A high-energy event launch experience built for attention, registrations and ticket conversion.',
    accent: '#ff69c7',
    secondary: '#8a5cff',
    stat: 'Built for launch day',
    tags: ['Event Launch', 'Registration', 'Media'],
    features: ['Cinematic event reveal and countdowns', 'Schedule, venue and speaker journeys', 'Registration and ticketing integration'],
    modes: ['Neon', 'Festival', 'Premiere'],
  },
  {
    id: 'brands',
    number: '06',
    eyebrow: 'Brands & agencies',
    title: 'Future Brand World',
    shortTitle: 'Brand',
    description: 'An expressive digital identity for ambitious companies that want to feel unmistakably modern.',
    accent: '#b4ff72',
    secondary: '#77f7d2',
    stat: 'Distinct by design',
    tags: ['Brand System', 'Motion Design', 'Storytelling'],
    features: ['Immersive brand-led art direction', 'Motion system and micro-interactions', 'Campaign, services and lead-generation flows'],
    modes: ['Signal', 'Aurora', 'Monochrome'],
  },
]

export const capabilities = [
  'WebGL & Three.js',
  'Interactive product design',
  'Real-time dashboards',
  'E-commerce experiences',
  'Booking & lead systems',
  'Responsive development',
  'Motion & micro-interactions',
  'Performance optimisation',
]
