export const demos = [
  {
    id: 'commerce',
    number: '01',
    eyebrow: 'E-commerce',
    title: '3D Product Studio',
    shortTitle: 'Commerce',
    description: 'A tactile product configurator that turns browsing into an interactive buying experience.',
    accent: '#77f7d2',
    secondary: '#4f7cff',
    stat: '+34% engagement',
    tags: ['3D Configurator', 'Cart-ready', 'Mobile-first'],
    features: ['Real-time colour and finish controls', 'Interactive orbit and product details', 'Conversion-focused product storytelling'],
    modes: ['Studio', 'Midnight', 'Editorial'],
  },
  {
    id: 'real-estate',
    number: '02',
    eyebrow: 'Real estate',
    title: 'Virtual Property Tour',
    shortTitle: 'Real Estate',
    description: 'An explorable property presentation designed to help buyers understand a project before a site visit.',
    accent: '#ffbd69',
    secondary: '#ff6f91',
    stat: '24/7 open house',
    tags: ['Virtual Tour', 'Lead Capture', 'Project Map'],
    features: ['Day and night environment modes', 'Interactive building visualisation', 'Brochure, enquiry and WhatsApp flows'],
    modes: ['Golden hour', 'Daylight', 'Night'],
  },
  {
    id: 'hospitality',
    number: '03',
    eyebrow: 'Hospitality',
    title: 'Immersive Dining',
    shortTitle: 'Hospitality',
    description: 'A cinematic restaurant experience with interactive menus, ambience and reservation journeys.',
    accent: '#ff8b7b',
    secondary: '#ffc857',
    stat: '2-click booking',
    tags: ['Interactive Menu', 'Reservations', 'Local SEO'],
    features: ['Visual signature-dish storytelling', 'Reservation and WhatsApp ordering', 'Events, offers and location integration'],
    modes: ['Chef table', 'Dinner', 'Celebration'],
  },
  {
    id: 'saas',
    number: '04',
    eyebrow: 'SaaS & dashboards',
    title: 'Live Intelligence',
    shortTitle: 'SaaS',
    description: 'A real-time command centre that makes complex business data easy to understand and act on.',
    accent: '#8d9cff',
    secondary: '#58e6ff',
    stat: '<1s live updates',
    tags: ['Live Data', 'Role-based UI', 'Analytics'],
    features: ['Streaming metric visualisation', 'Responsive operational dashboard', 'API, auth and notification-ready UI'],
    modes: ['Overview', 'Revenue', 'Operations'],
  },
  {
    id: 'events',
    number: '05',
    eyebrow: 'Events & entertainment',
    title: 'Digital Stage',
    shortTitle: 'Events',
    description: 'A high-energy event launch experience built for attention, registrations and ticket conversion.',
    accent: '#ff69c7',
    secondary: '#8a5cff',
    stat: 'Built for launch day',
    tags: ['Event Launch', 'Registration', 'Media'],
    features: ['Cinematic event reveal and countdowns', 'Schedule, venue and speaker journeys', 'Registration and ticketing integration'],
    modes: ['Neon', 'Festival', 'Premiere'],
  },
  {
    id: 'brands',
    number: '06',
    eyebrow: 'Brands & agencies',
    title: 'Future Brand World',
    shortTitle: 'Brand',
    description: 'An expressive digital identity for ambitious companies that want to feel unmistakably modern.',
    accent: '#b4ff72',
    secondary: '#77f7d2',
    stat: 'Distinct by design',
    tags: ['Brand System', 'Motion Design', 'Storytelling'],
    features: ['Immersive brand-led art direction', 'Motion system and micro-interactions', 'Campaign, services and lead-generation flows'],
    modes: ['Signal', 'Aurora', 'Monochrome'],
  },
  {
    id: 'education',
    number: '07',
    eyebrow: 'Schools & education',
    title: 'Connected Campus',
    shortTitle: 'Education',
    description: 'A modern school and institute experience that brings admissions, academics and campus stories together.',
    accent: '#ffd166',
    secondary: '#4f7cff',
    stat: 'Admissions-ready',
    tags: ['Admissions', 'Notices', 'Bilingual UI'],
    features: ['Online admissions and enquiry journeys', 'Notices, results, events and gallery CMS', 'Parent-friendly mobile and bilingual experience'],
    modes: ['Campus', 'Learning', 'Admissions'],
  },
  {
    id: 'fitness',
    number: '08',
    eyebrow: 'Fitness & wellness',
    title: 'Performance Arena',
    shortTitle: 'Fitness',
    description: 'A high-energy gym and wellness platform built to showcase programs, trainers and memberships.',
    accent: '#ff664f',
    secondary: '#ffc857',
    stat: 'Lead-focused',
    tags: ['Memberships', 'Schedules', 'Transformations'],
    features: ['Programs, trainers and class schedules', 'Membership enquiries and trial booking', 'Transformation stories and social proof'],
    modes: ['Strength', 'Cardio', 'Recovery'],
  },
  {
    id: 'healthcare',
    number: '09',
    eyebrow: 'Healthcare & clinics',
    title: 'Digital Care Desk',
    shortTitle: 'Healthcare',
    description: 'A calm, trustworthy clinic experience for services, doctors, appointments and patient guidance.',
    accent: '#64e6c4',
    secondary: '#4e8cff',
    stat: '24/7 appointments',
    tags: ['Appointments', 'Doctor Profiles', 'Patient UX'],
    features: ['Doctor and treatment discovery', 'Appointment and callback workflows', 'Accessible patient information architecture'],
    modes: ['Care', 'Consult', 'Insights'],
  },
  {
    id: 'travel',
    number: '10',
    eyebrow: 'Travel & tourism',
    title: 'Journey Explorer',
    shortTitle: 'Travel',
    description: 'An immersive travel storefront that turns destinations, packages and itineraries into bookable journeys.',
    accent: '#55d7ff',
    secondary: '#8b6dff',
    stat: 'Trip-planner ready',
    tags: ['Tour Packages', 'Trip Planner', 'WhatsApp Booking'],
    features: ['Destination and package storytelling', 'Custom itinerary and enquiry builder', 'Maps, weather and WhatsApp booking flows'],
    modes: ['Explore', 'Adventure', 'Retreat'],
  },
  {
    id: 'jewellery',
    number: '11',
    eyebrow: 'Jewellery & fashion',
    title: 'Luxury Collection Room',
    shortTitle: 'Luxury Retail',
    description: 'A premium catalogue experience for jewellery, fashion and handcrafted collections with rich product discovery.',
    accent: '#f6cf72',
    secondary: '#c58cff',
    stat: 'Luxury commerce',
    tags: ['Collections', 'Lookbook', 'Product Enquiry'],
    features: ['Collection-led product discovery', 'Interactive lookbooks and detail views', 'Catalogue, enquiry and commerce integrations'],
    modes: ['Gold', 'Emerald', 'Pearl'],
  },
  {
    id: 'sports',
    number: '12',
    eyebrow: 'Sports & academies',
    title: 'Live Sports Hub',
    shortTitle: 'Sports',
    description: 'A real-time sports platform for academies, federations, tournaments, registrations and live results.',
    accent: '#9cff57',
    secondary: '#2ecbff',
    stat: 'Live-score ready',
    tags: ['Registrations', 'Fixtures', 'Live Results'],
    features: ['Tournament registration and player profiles', 'Fixtures, standings and live result updates', 'Academy programs, media and announcements'],
    modes: ['Matchday', 'Academy', 'Tournament'],
  },
]

export const capabilities = [
  'WebGL & Three.js',
  'Interactive product design',
  'Real-time dashboards',
  'E-commerce experiences',
  'Booking & lead systems',
  'Responsive development',
  'Motion & micro-interactions',
  'Performance optimisation',
  'Admissions & portals',
  'Appointments & schedules',
  'Live scores & updates',
  'CMS & multilingual content',
]
