const image = (id, width = 1600) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${width}&q=82`

export const realWorldSites = [
  {
    id: 'restaurant',
    industry: 'Restaurant & hospitality',
    brand: 'Ember & Oak',
    kicker: 'Modern Indian dining · Indore',
    headline: 'Fire-led flavours. Thoughtful hospitality.',
    description: 'A cinematic restaurant website with a live menu, table reservation flow, gallery and direct ordering actions.',
    heroImage: image('1517248135467-4c7edcad34c4'),
    video: 'https://cdn.coverr.co/videos/coverr-chef-cooking-in-a-restaurant-3327/1080p.mp4',
    videoCredit: 'https://coverr.co/videos/chef-cooking-in-a-restaurant-d7i8bxpc5k',
    accent: '#ef9a62',
    accent2: '#ffd19b',
    background: '#100b08',
    surface: '#1b130e',
    text: '#fff8f0',
    muted: '#b9a99d',
    status: 'Dinner service open',
    liveLabel: 'Tables available tonight',
    primaryAction: 'Reserve a table',
    secondaryAction: 'Explore the menu',
    sectionLabel: 'Seasonal menu',
    sectionTitle: 'Made for memorable evenings.',
    stats: [['4.9/5', 'Guest rating'], ['12–11 PM', 'Open daily'], ['18 min', 'Avg. response']],
    categories: ['All', 'Small plates', 'Mains', 'Dessert'],
    items: [
      { category: 'Small plates', title: 'Tandoor Broccoli', text: 'Smoked almond, hung curd and chilli oil.', meta: '₹385' },
      { category: 'Small plates', title: 'Charred Corn Chaat', text: 'Citrus, pomegranate and house masala.', meta: '₹295' },
      { category: 'Mains', title: 'Dal Ember', text: 'Slow-cooked black lentils finished over charcoal.', meta: '₹445' },
      { category: 'Mains', title: 'Forest Mushroom Kulcha', text: 'Wild mushroom, truffle and smoked cheese.', meta: '₹395' },
      { category: 'Dessert', title: 'Saffron Milk Cake', text: 'Pistachio, rose and warm rabri.', meta: '₹325' },
    ],
    features: ['Instant table request', 'WhatsApp ordering', 'Live menu filters', 'Maps-ready location'],
    gallery: [image('1414235077428-338989a2e8c0'), image('1515003197210-e0cd71810b5f'), image('1517248135467-4c7edcad34c4')],
    quote: 'Every detail—from the first scroll to the final reservation—is designed to feel like the restaurant itself.',
    formTitle: 'Plan your table',
    formPrompt: 'Share your preferred date, time and group size.',
  },
  {
    id: 'fitness',
    industry: 'Gym & fitness',
    brand: 'Iron Pulse',
    kicker: 'Strength · Movement · Community',
    headline: 'Build strength that shows up everywhere.',
    description: 'A performance-first gym website with programs, trainer discovery, class schedules and trial-session booking.',
    heroImage: image('1534438327276-14e5300c3a48'),
    video: 'https://cdn.coverr.co/videos/coverr-man-training-in-the-gym-8192/1080p.mp4',
    videoCredit: 'https://coverr.co/videos/man-training-in-the-gym-cteqfqomrh',
    accent: '#ff5d3f',
    accent2: '#ffc857',
    background: '#090a0b',
    surface: '#151719',
    text: '#f7f7f5',
    muted: '#a6aaa9',
    status: 'Gym floor live',
    liveLabel: 'Trial slots this week',
    primaryAction: 'Book a free trial',
    secondaryAction: 'View programs',
    sectionLabel: 'Training programs',
    sectionTitle: 'A program for every starting point.',
    stats: [['5 AM–11 PM', 'Daily access'], ['12+', 'Expert coaches'], ['34', 'Classes weekly']],
    categories: ['All', 'Strength', 'Conditioning', 'Recovery'],
    items: [
      { category: 'Strength', title: 'Foundation Strength', text: 'Technique-led barbell and functional training.', meta: 'Beginner' },
      { category: 'Strength', title: 'Performance Lab', text: 'Progressive training for experienced athletes.', meta: 'Advanced' },
      { category: 'Conditioning', title: 'Pulse 45', text: 'Fast, coached full-body conditioning sessions.', meta: '45 min' },
      { category: 'Conditioning', title: 'Athletic Engine', text: 'Speed, agility and power development.', meta: '60 min' },
      { category: 'Recovery', title: 'Mobility Reset', text: 'Guided movement and active recovery.', meta: '30 min' },
    ],
    features: ['Live class schedule', 'Trial booking', 'Trainer profiles', 'Membership enquiries'],
    gallery: [image('1571019613454-1cb2f99b2d8b'), image('1581009146145-b5ef050c2e1e'), image('1534438327276-14e5300c3a48')],
    quote: 'A bold digital experience that turns motivation into a simple next step: book, visit and begin.',
    formTitle: 'Start your trial',
    formPrompt: 'Tell us your preferred training time and goal.',
  },
  {
    id: 'education',
    industry: 'School & education',
    brand: 'Northstar Academy',
    kicker: 'Learning with purpose · Admissions 2026–27',
    headline: 'Curious minds become confident futures.',
    description: 'A complete school website concept with admissions, academics, notices, campus life and parent-friendly enquiry flows.',
    heroImage: image('1509062522246-3755977927d7'),
    accent: '#ffd45a',
    accent2: '#77b7ff',
    background: '#07182d',
    surface: '#102640',
    text: '#f6fbff',
    muted: '#a6bbcf',
    status: 'Admissions open',
    liveLabel: 'Campus tour slots',
    primaryAction: 'Apply for admission',
    secondaryAction: 'Explore academics',
    sectionLabel: 'Learning pathways',
    sectionTitle: 'A balanced education, built around every learner.',
    stats: [['18:1', 'Student–teacher ratio'], ['25+', 'Clubs & sports'], ['100%', 'Digital notices']],
    categories: ['All', 'Academics', 'Campus', 'Admissions'],
    items: [
      { category: 'Academics', title: 'Foundation Years', text: 'Play-led, language-rich early learning.', meta: 'Nursery–II' },
      { category: 'Academics', title: 'Middle School', text: 'Concepts, creativity and collaborative learning.', meta: 'III–VIII' },
      { category: 'Campus', title: 'Sports & Movement', text: 'Daily physical education and team programs.', meta: '25+ activities' },
      { category: 'Campus', title: 'Arts & Innovation', text: 'Music, visual arts, robotics and maker spaces.', meta: 'Weekly labs' },
      { category: 'Admissions', title: 'Campus Tour', text: 'Meet educators and experience the school day.', meta: 'Book online' },
    ],
    features: ['Online admission enquiry', 'Notice board', 'Bilingual-ready content', 'Parent mobile experience'],
    gallery: [image('1523240795612-9a054b0db644'), image('1509062522246-3755977927d7'), image('1562774053-701939374585')],
    quote: 'Clear information for parents, energetic stories for students and simple tools for the school team.',
    formTitle: 'Admission enquiry',
    formPrompt: 'Share the class and preferred campus-tour date.',
  },
  {
    id: 'travel',
    industry: 'Travel & tourism',
    brand: 'Terra Trails',
    kicker: 'Curated journeys across India',
    headline: 'Travel slowly. Remember everything.',
    description: 'An immersive tourism website with destination filters, real package cards, itinerary enquiry and direct trip planning.',
    heroImage: image('1507525428034-b723cf961d3e'),
    video: 'https://cdn.coverr.co/videos/coverr-overlooking-the-mountains-8002/1080p.mp4',
    videoCredit: 'https://coverr.co/videos/overlooking-the-mountains-b1u9fiuohy',
    accent: '#5ee8c3',
    accent2: '#7cbcff',
    background: '#071614',
    surface: '#102521',
    text: '#f2fffb',
    muted: '#a6c1ba',
    status: 'Travel desk online',
    liveLabel: 'Custom plans today',
    primaryAction: 'Plan my trip',
    secondaryAction: 'Browse journeys',
    sectionLabel: 'Featured journeys',
    sectionTitle: 'Trips designed around how you want to feel.',
    stats: [['40+', 'Curated routes'], ['4.8/5', 'Traveller rating'], ['24 hr', 'Plan response']],
    categories: ['All', 'Mountains', 'Beaches', 'Culture'],
    items: [
      { category: 'Mountains', title: 'Himalayan Slow Road', text: 'Himachal villages, forest walks and local stays.', meta: '7 days' },
      { category: 'Mountains', title: 'Kashmir Valleys', text: 'Lakes, meadows and a relaxed mountain itinerary.', meta: '6 days' },
      { category: 'Beaches', title: 'Konkan Coast', text: 'Quiet beaches, coastal food and heritage towns.', meta: '5 days' },
      { category: 'Culture', title: 'Royal Rajasthan', text: 'Forts, craft trails and desert evenings.', meta: '8 days' },
      { category: 'Culture', title: 'Heart of Madhya Pradesh', text: 'Wildlife, history and local experiences.', meta: '6 days' },
    ],
    features: ['Package filters', 'Custom trip planner', 'WhatsApp itinerary', 'Weather-ready UI'],
    gallery: [image('1469474968028-56623f02e42e'), image('1470770841072-f978cf4d019e'), image('1507525428034-b723cf961d3e')],
    quote: 'Real destination imagery and a frictionless enquiry journey make every trip feel possible.',
    formTitle: 'Build your itinerary',
    formPrompt: 'Share your destination, dates and number of travellers.',
  },
  {
    id: 'real-estate',
    industry: 'Real estate',
    brand: 'Verdant Estates',
    kicker: 'Design-led homes · Indore',
    headline: 'A quieter way to live in the city.',
    description: 'A premium property website with project storytelling, unit filters, virtual-tour entry points and site-visit booking.',
    heroImage: image('1600585154340-be6161a56a0c'),
    accent: '#d4f08a',
    accent2: '#e9c989',
    background: '#10130d',
    surface: '#1d2218',
    text: '#fbfff4',
    muted: '#b5bea7',
    status: 'Sales lounge open',
    liveLabel: 'Site visits available',
    primaryAction: 'Book a site visit',
    secondaryAction: 'View residences',
    sectionLabel: 'Available residences',
    sectionTitle: 'Spaces shaped around light, air and everyday life.',
    stats: [['8.5 acres', 'Green campus'], ['2028', 'Possession'], ['IGBC', 'Pre-certified']],
    categories: ['All', '2 BHK', '3 BHK', 'Villas'],
    items: [
      { category: '2 BHK', title: 'Garden Residence', text: 'Efficient plan with balcony and garden outlook.', meta: '1,180 sq ft' },
      { category: '3 BHK', title: 'Courtyard Home', text: 'Large living spaces with cross ventilation.', meta: '1,760 sq ft' },
      { category: '3 BHK', title: 'Sky Residence', text: 'Upper-floor home with extended deck.', meta: '1,940 sq ft' },
      { category: 'Villas', title: 'Park Villa', text: 'Private garden, flexible family spaces and terrace.', meta: '2,850 sq ft' },
    ],
    features: ['Unit filters', 'Site-visit booking', 'Brochure journey', 'Maps & WhatsApp'],
    gallery: [image('1600607687939-ce8a6c25118c'), image('1600566753190-17f0baa2a6c3'), image('1600585154340-be6161a56a0c')],
    quote: 'A considered digital sales experience helps buyers understand the project before they ever reach the site.',
    formTitle: 'Book a private visit',
    formPrompt: 'Choose your preferred residence and visit time.',
  },
  {
    id: 'jewellery',
    industry: 'Jewellery & fashion',
    brand: 'Aurelia House',
    kicker: 'Fine jewellery · Crafted in India',
    headline: 'Modern heirlooms, made to be lived in.',
    description: 'A refined luxury catalogue with collection filters, image-led product stories and personalised enquiry actions.',
    heroImage: image('1515562141207-7a88fb7ce338'),
    accent: '#b68a35',
    accent2: '#e9cf93',
    background: '#f5f0e7',
    surface: '#fffaf2',
    text: '#221a10',
    muted: '#736755',
    status: 'Stylist online',
    liveLabel: 'Private appointments',
    primaryAction: 'Book a consultation',
    secondaryAction: 'View collections',
    sectionLabel: 'Signature collections',
    sectionTitle: 'Crafted with restraint. Remembered for years.',
    stats: [['18K', 'Hallmarked gold'], ['30 days', 'Craft timeline'], ['1:1', 'Styling service']],
    categories: ['All', 'Gold', 'Diamond', 'Bridal'],
    items: [
      { category: 'Gold', title: 'Sona Line', text: 'Lightweight forms inspired by Indian geometry.', meta: '18K gold' },
      { category: 'Diamond', title: 'Orbit Studs', text: 'Everyday brilliance with a sculptural profile.', meta: 'Lab certified' },
      { category: 'Diamond', title: 'Arc Pendant', text: 'A clean solitaire setting with fine chain.', meta: 'Made to order' },
      { category: 'Bridal', title: 'Mogra Set', text: 'A contemporary bridal suite with handcrafted detail.', meta: 'Private viewing' },
    ],
    features: ['Collection filters', 'High-resolution gallery', 'Product enquiry', 'Consultation booking'],
    gallery: [image('1605100804763-247f67b3557e'), image('1599643478518-a784e5dc4c8f'), image('1515562141207-7a88fb7ce338')],
    quote: 'A calm, editorial experience lets craftsmanship lead while every product remains easy to enquire about.',
    formTitle: 'Private consultation',
    formPrompt: 'Tell us the collection, occasion and preferred appointment time.',
  },
  {
    id: 'healthcare',
    industry: 'Clinic & healthcare',
    brand: 'Nivara Clinic',
    kicker: 'Everyday care · Clear guidance',
    headline: 'Healthcare that begins with listening.',
    description: 'A reassuring clinic website with services, doctor availability, appointment requests and accessible patient information.',
    heroImage: image('1538108149393-fbbd81895907'),
    accent: '#25b99a',
    accent2: '#79c8ff',
    background: '#f2f8f7',
    surface: '#ffffff',
    text: '#102b28',
    muted: '#5f7773',
    status: 'Appointments open',
    liveLabel: 'Consultation slots',
    primaryAction: 'Request appointment',
    secondaryAction: 'Explore services',
    sectionLabel: 'Care services',
    sectionTitle: 'The right care, explained simply.',
    stats: [['8 AM–8 PM', 'Clinic hours'], ['6', 'Specialist doctors'], ['15 min', 'Response time']],
    categories: ['All', 'Primary care', 'Specialists', 'Diagnostics'],
    items: [
      { category: 'Primary care', title: 'General Consultation', text: 'Everyday health concerns and ongoing care.', meta: 'Same-day slots' },
      { category: 'Specialists', title: 'Paediatrics', text: 'Thoughtful care for children and families.', meta: 'Mon–Sat' },
      { category: 'Specialists', title: 'Physiotherapy', text: 'Movement assessment and guided rehabilitation.', meta: 'By appointment' },
      { category: 'Diagnostics', title: 'Preventive Screening', text: 'Simple health checks with clear follow-up.', meta: 'Packages available' },
    ],
    features: ['Appointment request', 'Doctor availability', 'Accessible content', 'Call & directions'],
    gallery: [image('1576091160399-112ba8d25d1d'), image('1519494026892-80bbd2d6fd0d'), image('1538108149393-fbbd81895907')],
    quote: 'Trust comes from clarity: accessible information, calm design and an appointment path that never feels confusing.',
    formTitle: 'Request an appointment',
    formPrompt: 'Share the service, preferred date and a short note.',
  },
  {
    id: 'sports',
    industry: 'Sports & academy',
    brand: 'NextPlay Academy',
    kicker: 'Football development · Ages 6–18',
    headline: 'Train smart. Play brave. Grow together.',
    description: 'A dynamic sports academy platform with age-group programs, registrations, fixtures, updates and trial-session booking.',
    heroImage: image('1461896836934-ffe607ba8211'),
    accent: '#a6ff4d',
    accent2: '#51c9ff',
    background: '#07100a',
    surface: '#111d14',
    text: '#f4fff0',
    muted: '#a7b8a3',
    status: 'Training day live',
    liveLabel: 'Trial sessions left',
    primaryAction: 'Register for a trial',
    secondaryAction: 'View programs',
    sectionLabel: 'Player pathways',
    sectionTitle: 'Development that matches the player.',
    stats: [['6–18 yrs', 'Age groups'], ['4', 'Weekly sessions'], ['12+', 'Qualified coaches']],
    categories: ['All', 'Foundation', 'Youth', 'Elite'],
    items: [
      { category: 'Foundation', title: 'First Touch', text: 'Fun, coordination and confidence through football.', meta: 'Ages 6–9' },
      { category: 'Youth', title: 'Player Development', text: 'Technical skills, game understanding and teamwork.', meta: 'Ages 10–13' },
      { category: 'Youth', title: 'Match Centre', text: 'Competitive fixtures with guided reflection.', meta: 'Weekly' },
      { category: 'Elite', title: 'Performance Squad', text: 'Position-specific coaching and match preparation.', meta: 'Ages 14–18' },
    ],
    features: ['Player registration', 'Fixtures & results', 'Age-group filters', 'Trial booking'],
    gallery: [image('1526232761682-d26e03ac148e'), image('1579952363873-27f3bade9f55'), image('1461896836934-ffe607ba8211')],
    quote: 'The site turns energy into action with clear pathways for players, parents, coaches and tournament visitors.',
    formTitle: 'Book a trial session',
    formPrompt: 'Share the player age group and preferred training day.',
  },
]

export const mediaCredits = {
  images: 'Photography is loaded from Unsplash under the Unsplash License.',
  videos: 'Selected hero footage is loaded from Coverr with commercial-use rights.',
}
